const products = [
    // Mobiles
    { name: 'Samsung Galaxy S21', price: 799.99, color: 'Phantom Gray', category: 'Mobile', discount: 10, description: 'Latest Samsung smartphone.', stock: 50 },
    { name: 'iPhone 13', price: 999.99, color: 'Starlight', category: 'Mobile', discount: 5, description: 'Latest iPhone with A15 chip.', stock: 30 },
    { name: 'Google Pixel 6', price: 599.99, color: 'Sorta Seafoam', category: 'Mobile', discount: 0, description: 'Google\'s flagship smartphone.', stock: 40 },
    { name: 'OnePlus 9', price: 729.99, color: 'Winter Mist', category: 'Mobile', discount: 15, description: 'High-performance smartphone with great camera.', stock: 20 },
    { name: 'Sony Xperia 1 III', price: 1299.99, color: 'Black', category: 'Mobile', discount: 0, description: 'Sony\'s premium smartphone.', stock: 15 },
    { name: 'Xiaomi Mi 11', price: 749.99, color: 'Horizon Blue', category: 'Mobile', discount: 5, description: 'Flagship smartphone from Xiaomi.', stock: 25 },
    { name: 'Nokia G20', price: 199.99, color: 'Night', category: 'Mobile', discount: 0, description: 'Budget smartphone with great battery life.', stock: 60 },
    { name: 'Oppo Find X3 Pro', price: 1149.99, color: 'Gloss Black', category: 'Mobile', discount: 0, description: 'High-end smartphone with cutting-edge features.', stock: 10 },
    { name: 'Motorola Edge 20', price: 499.99, color: 'Frosted Emerald', category: 'Mobile', discount: 7, description: 'Mid-range smartphone with great specs.', stock: 35 },
    { name: 'Asus Zenfone 8', price: 699.99, color: 'Moonlight White', category: 'Mobile', discount: 20, description: 'Pure Android experience in a compact size.', stock: 45 },

    // Laptops
    { name: 'Dell XPS 13', price: 1099.99, color: 'Silver', category: 'Laptop', discount: 15, description: 'High-end laptop with great performance.', stock: 20 },
    { name: 'Apple MacBook Air', price: 999.99, color: 'Space Gray', category: 'Laptop', discount: 0, description: 'The ultra-lightweight laptop from Apple.', stock: 25 },
    { name: 'Lenovo ThinkPad X1 Carbon', price: 1399.99, color: 'Black', category: 'Laptop', discount: 10, description: 'Lightweight business laptop.', stock: 30 },
    { name: 'HP Spectre x360', price: 1249.99, color: 'Gem Cut', category: 'Laptop', discount: 10, description: 'Stylish convertible laptop with great features.', stock: 15 },
    { name: 'Razer Blade 15', price: 1999.99, color: 'Black', category: 'Laptop', discount: 0, description: 'Gaming laptop with powerful hardware.', stock: 10 },
    { name: 'Asus ROG Zephyrus G14', price: 1499.99, color: 'Moonlight White', category: 'Laptop', discount: 5, description: 'Compact gaming laptop with AMD Ryzen chipset.', stock: 10 },
    { name: 'Microsoft Surface Laptop 4', price: 999.99, color: 'Matte Black', category: 'Laptop', discount: 0, description: 'Elegant laptop with touchscreen display.', stock: 20 },
    { name: 'Acer Swift 3', price: 699.99, color: 'Silver', category: 'Laptop', discount: 5, description: 'Affordable ultrabook with great battery life.', stock: 25 },
    { name: 'LG Gram 17', price: 1799.99, color: 'Dark Silver', category: 'Laptop', discount: 0, description: 'Super lightweight 17-inch laptop.', stock: 5 },
    { name: 'Huawei MateBook X Pro', price: 1399.99, color: 'Space Gray', category: 'Laptop', discount: 10, description: 'Laptop with stunning 3K display.', stock: 15 },

    // Earbuds
    { name: 'Apple AirPods Pro', price: 249.99, color: 'White', category: 'Earbuds', discount: 0, description: 'Noise cancelling true wireless earbuds.', stock: 100 },
    { name: 'Sony WF-1000XM4', price: 279.99, color: 'Black', category: 'Earbud', discount: 20, description: 'Industry-leading noise cancelling earbuds.', stock: 70 },
    { name: 'Bose QuietComfort Earbuds', price: 279.99, color: 'Black', category: 'Earbud', discount: 10, description: 'High-quality noise cancelling earbuds.', stock: 50 },
    { name: 'Jabra Elite 85t', price: 229.99, color: 'Titanium Black', category: 'Earbud', discount: 5, description: 'Great sound and active noise cancellation.', stock: 80 },
    { name: 'Samsung Galaxy Buds Pro', price: 199.99, color: 'Phantom Violet', category: 'Earbud', discount: 0, description: 'Premium earbuds with great sound quality.', stock: 40 },
    { name: 'Anker Soundcore Liberty Air 2', price: 99.99, color: 'White', category: 'Earbud', discount: 20, description: 'Affordable earbuds with solid performance.', stock: 60 },
    { name: 'Sennheiser Momentum True Wireless 2', price: 299.99, color: 'Black', category: 'Earbud', discount: 0, description: 'High-quality audio in a compact form.', stock: 30 },
    { name: 'Beats Studio Buds', price: 149.99, color: 'Black', category: 'Earbud', discount: 5, description: 'Comfortable fit with great sound quality.', stock: 45 },
    { name: 'OnePlus Buds Pro', price: 149.99, color: 'White', category: 'Earbud', discount: 10, description: 'Active noise cancellation and long battery life.', stock: 55 },
    { name: 'Shure AONIC 215', price: 199.99, color: 'Clear', category: 'Earbud', discount: 0, description: 'Professional quality sound with detachable cable.', stock: 25 },

    // Shoes
    { name: 'Nike Air Max 270', price: 149.99, color: 'Black/White', category: 'Shoes', discount: 10, description: 'Comfortable running shoes.', stock: 40 },
    { name: 'Adidas Ultraboost', price: 179.99, color: 'Triple Black', category: 'Shoes', discount: 5, description: 'High-performance running shoes.', stock: 60 },
    { name: 'Puma RS-X', price: 110.00, color: 'White/Blue', category: 'Shoes', discount: 15, description: 'Retro sneakers with a modern twist.', stock: 30 },
    { name: 'Reebok Classic Leather', price: 75.00, color: 'White', category: 'Shoes', discount: 5, description: 'Timeless classic sneaker.', stock: 50 },
    { name: 'New Balance 990v5', price: 185.00, color: 'Grey', category: 'Shoes', discount: 0, description: 'Stylish and comfortable everyday shoe.', stock: 20 },
    { name: 'Vans Old Skool', price: 60.00, color: 'Black/White', category: 'Shoes', discount: 10, description: 'Classic skate style.', stock: 55 },
    { name: 'Under Armour HOVR Phantom', price: 150.00, color: 'Black', category: 'Shoes', discount: 0, description: 'Performance shoe with amazing comfort.', stock: 15 },
    { name: 'Converse Chuck Taylor All Star', price: 55.00, color: 'Red', category: 'Shoes', discount: 0, description: 'Classic canvas sneakers.', stock: 70 },
    { name: 'Hoka One One Bondi 7', price: 160.00, color: 'Black', category: 'Shoes', discount: 0, description: 'Maximum cushioning for those long runs.', stock: 10 },
    { name: 'On Cloudstratus', price: 170.00, color: 'Dark Blue', category: 'Shoes', discount: 15, description: 'Lightweight and supportive running shoe.', stock: 40 },
  
    // Speakers
    { name: 'JBL Charge 4', price: 179.99, color: 'Black', category: 'Speaker', discount: 15, description: 'Portable Bluetooth speaker with great sound.', stock: 200 },
    { name: 'Sonos One', price: 199.99, color: 'White', category: 'Speaker', discount: 0, description: 'Smart speaker with Alexa and Google Assistant.', stock: 150 },
    { name: 'Bose SoundLink Revolve+', price: 329.99, color: 'Lux Gray', category: 'Speaker', discount: 10, description: '360-degree sound for consistent coverage.', stock: 60 },
    { name: 'Ultimate Ears MEGABOOM 3', price: 199.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Powerful, portable speaker with a 20-hour battery.', stock: 80 },
    { name: 'Anker Soundcore 2', price: 49.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Compact and budget-friendly Bluetooth speaker.', stock: 100 },
    { name: 'Apple HomePod mini', price: 99.99, color: 'Space Gray', category: 'Speaker', discount: 0, description: 'Smart speaker with Siri integration.', stock: 90 },
    { name: 'Samsung Galaxy Home', price: 149.99, color: 'Black', category: 'Speaker', discount: 5, description: 'Smart speaker with Bixby.', stock: 40 },
    { name: 'Bose Portable Smart Speaker', price: 349.99, color: 'Silver', category: 'Speaker', discount: 0, description: 'Bluetooth speaker with high-quality sound.', stock: 25 },
    { name: 'Marshall Emberton', price: 149.99, color: 'Black', category: 'Speaker', discount: 10, description: 'Stylish portable speaker with classic design.', stock: 75 },
    { name: 'Google Nest Audio', price: 99.99, color: 'Charcoal', category: 'Speaker', discount: 0, description: 'Smart speaker with Google Assistant.', stock: 80 },
    
    // Additional products to reach 100.
    { name: 'Asus ROG Phone 5', price: 999.99, color: 'Phantom Black', category: 'Mobile', discount: 0, description: 'Gaming smartphone with high refresh rate.', stock: 20 },
    { name: 'Xiaomi Redmi Note 10', price: 199.99, color: 'Onyx Gray', category: 'Mobile', discount: 0, description: 'Affordable smartphone with good specs.', stock: 50 },
    { name: 'Nokia 3310', price: 49.99, color: 'Blue', category: 'Mobile', discount: 0, description: 'Classic mobile phone.', stock: 100 },
    { name: 'MacBook Pro 16"', price: 2399.99, color: 'Space Gray', category: 'Laptop', discount: 0, description: 'Powerful laptop for professionals.', stock: 15 },
    { name: 'HP Pavilion 15', price: 649.99, color: 'Silver', category: 'Laptop', discount: 5, description: 'Affordable laptop for everyday tasks.', stock: 30 },
    { name: 'Lenovo IdeaPad 3', price: 599.99, color: 'Cloud Grey', category: 'Laptop', discount: 10, description: 'Budget-friendly laptop for learning.', stock: 20 },
    { name: 'Acer Aspire 5', price: 549.99, color: 'Silver', category: 'Laptop', discount: 0, description: 'Reliable laptop for students.', stock: 30 },
    { name: 'Razer Blade Stealth 13', price: 1799.99, color: 'Black', category: 'Laptop', discount: 5, description: 'Compact gaming ultrabook.', stock: 10 },
    { name: 'Alienware m15 R5', price: 2099.99, color: 'Lunar Light', category: 'Laptop', discount: 0, description: 'High-performance gaming laptop.', stock: 5 },
    { name: 'Logitech G Pro X', price: 149.99, color: 'Blue', category: 'Earbud', discount: 0, description: 'Gaming earbuds with excellent sound quality.', stock: 60 },
    { name: 'Sennheiser IE 80 S', price: 349.99, color: 'Black', category: 'Earbud', discount: 20, description: 'High fidelity in-ear headphones.', stock: 30 },
    { name: 'Shure SE215', price: 99.99, color: 'Clear', category: 'Earbud', discount: 0, description: 'Comfortable and high-quality in-ear earbuds.', stock: 50 },
    { name: 'Beats Flex', price: 49.99, color: 'Black', category: 'Earbud', discount: 0, description: 'Affordable wireless earbuds with great audio.', stock: 80 },
    { name: 'Bose QuietComfort Earbuds II', price: 299.99, color: 'Black', category: 'Earbud', discount: 10, description: 'Comfortable earbuds with top-notch noise cancelling.', stock: 25 },
    { name: 'Nike Air Force 1', price: 90.00, color: 'White', category: 'Shoes', discount: 10, description: 'Classic white sneakers.', stock: 45 },
    { name: 'Adidas Superstar', price: 85.00, color: 'White/Black', category: 'Shoes', discount: 0, description: 'Iconic leather shoes.', stock: 60 },
    { name: 'Puma RS 2.0', price: 110.00, color: 'White/Red', category: 'Shoes', discount: 5, description: 'Stylish sneakers for everyday wear.', stock: 50 },
    { name: 'New Balance Fresh Foam', price: 120.00, color: 'Black', category: 'Shoes', discount: 5, description: 'Running shoes with excellent cushioning.', stock: 40 },
    { name: 'Hoka One One Clifton 8', price: 140.00, color: 'Blue', category: 'Shoes', discount: 0, description: 'Lightweight and cushioned running shoes.', stock: 30 },
    { name: 'Bose SoundLink Mini II', price: 179.99, color: 'Silver', category: 'Speaker', discount: 0, description: 'Compact Bluetooth speaker with superb sound.', stock: 150 },
    { name: 'Anker Soundcore Motion+ Speaker', price: 99.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Portable speaker with rich sound.', stock: 100 },
    { name: 'Harman Kardon Onyx Studio 6', price: 449.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Elegant design and great sound quality.', stock: 25 },
    { name: 'Sonos Roam', price: 179.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Portable smart speaker with great sound.', stock: 80 },
    { name: 'JBL Flip 5', price: 89.99, color: 'Red', category: 'Speaker', discount: 5, description: 'Compact Bluetooth speaker with powerful sound.', stock: 100 },
    { name: 'Amazon Echo Dot (4th Gen)', price: 49.99, color: 'Charcoal', category: 'Speaker', discount: 0, description: 'Smart speaker activated by voice.', stock: 90 },
    { name: 'Google Nest Mini', price: 49.99, color: 'Chalk', category: 'Speaker', discount: 0, description: 'Voice-controlled speaker with Google Assistant.', stock: 85 },
    { name: 'MarshallWoburn II', price: 599.99, color: 'Black', category: 'Speaker', discount: 0, description: 'High-end speaker with retro design and powerful sound.', stock: 10 },
    { name: 'Ultimate Ears BOOM 3', price: 149.99, color: 'Black', category: 'Speaker', discount: 0, description: 'Rugged Bluetooth speaker with amazing sound.', stock: 80 },
    { name: 'DAKOTA E187', price: 229.99, color: 'Burgundy', category: 'Shoes', discount: 0, description: 'Comfortable and stylish footwear.', stock: 25 },
    { name: 'Fossil Gen 5 Smartwatch', price: 349.99, color: 'Black', category: 'Wearable', discount: 10, description: 'Stylish smartwatch with fitness features.', stock: 50 },
    { name: 'Skullcandy Riff Wireless', price: 59.99, color: 'Blue', category: 'Earbud', discount: 10, description: 'Wireless headphones with powerful bass.', stock: 100 },
    { name: 'HP Omen 15 Gaming Laptop', price: 1299.99, color: 'Black', category: 'Laptop', discount: 0, description: 'High-performance gaming laptop.', stock: 5 },
    { name: 'Dell G3 15', price: 999.99, color: 'Black', category: 'Laptop', discount: 5, description: 'Affordable gaming laptop.', stock: 10 },
    { name: 'Acer Predator Helios 300', price: 1399.99, color: 'Black', category: 'Laptop', discount: 10, description: 'Gaming laptop with powerful specs.', stock: 5 },
    { name: 'Razer Blade 15 Advanced', price: 2499.99, color: 'Black', category: 'Laptop', discount: 0, description: 'Premium gaming laptop.', stock: 3 },
    { name: 'Lenovo Legion 5', price: 1199.99, color: 'Gray', category: 'Laptop', discount: 5, description: 'Gaming laptop with AMD Ryzen.', stock: 10 },
    { name: 'Asus ZenBook 13', price: 849.99, color: 'Grey', category: 'Laptop', discount: 0, description: 'Lightweight business laptop.', stock: 20 },
    { name: 'Microsoft Surface Go 2', price: 399.99, color: 'Platinum', category: 'Tablet', discount: 0, description: 'Versatile tablet with Windows OS.', stock: 15 },
    { name: 'Apple iPad Air (2020)', price: 599.99, color: 'Space Gray', category: 'Tablet', discount: 0, description: 'Powerful tablet with A14 chip.', stock: 25 },
    { name: 'Samsung Galaxy Tab S7', price: 649.99, color: 'Mystic Bronze', category: 'Tablet', discount: 0, description: 'High-performance Android tablet.', stock: 15 },
    { name: 'Wacom Intuos Drawing Tablet', price: 79.99, color: 'Black', category: 'Tablet', discount: 0, description: 'Best tablet for artists and designers.', stock: 40 },
    { name: 'Oculus Quest 2', price: 299.99, color: 'White', category: 'VR', discount: 0, description: 'All-in-one VR headset with gaming capabilities.', stock: 20 },
    { name: 'HTC Vive Pro 2', price: 799.99, color: 'Black', category: 'VR', discount: 0, description: 'Premium VR headset for the ultimate experience.', stock: 15 },
    { name: 'Sony PlayStation VR', price: 399.99, color: 'White', category: 'VR', discount: 0, description: 'VR headset compatible with PS4 and PS5.', stock: 10 },
    { name: 'Simply Fit Board', price: 39.99, color: 'Blue', category: 'Fitness', discount: 0, description: 'Fun balance board for fitness workouts.', stock: 60 },
    { name: 'FitBit Charge 5', price: 179.99, color: 'Graphite', category: 'Fitness', discount: 0, description: 'Advanced health and fitness tracker.', stock: 30 },
    { name: 'Garmin Forerunner 245', price: 349.99, color: 'Black', category: 'Fitness', discount: 5, description: 'GPS running watch with heart rate monitor.', stock: 25 }
];

// Export the products array
module.exports = products;